import type { Metadata } from 'next';
import 'react-datepicker/dist/react-datepicker.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next Pets App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
